import { viewFunction } from "../helpers";
import type { PublicArgsInterface } from "../interfaces";

/**
 * View Is Withdraw Valid
 * @param rpcUrl The Current Near RPC Url
 * @param contract The HYC registry accountId
 * @param currencyContract The instance accountId to check if withdraw is valid
 * @param payload The public args generated by plonk
 * @returns {Promise<any>}
 */
export const viewIsWithdrawValid = async (
  rpcUrl: string,
  contract: string,
  currencyContract: string,
  payload: PublicArgsInterface
): Promise<boolean> => {
  const withdrawIsValid = await viewFunction(
    rpcUrl,
    currencyContract,
    "view_is_withdraw_valid",
    payload
  );

  const rootAllowlistIsValid = await viewFunction(
    rpcUrl,
    contract,
    "view_is_allowlist_root_valid",
    {
      root: payload.allowlist_root,
    }
  );

  return withdrawIsValid && rootAllowlistIsValid;
};
